FROM python:3.12

WORKDIR /app

#COPY pyproject.toml poetry.lock ./
COPY pyproject.toml poetry.lock /app/

#RUN pip install virtualenv
RUN pip install poetry
RUN poetry install
EXPOSE 8085

COPY . /app

CMD ["poetry", "run", "uvicorn", "todoapp.main:app", "--host", "0.0.0.0", "--port", "8085"]
